<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInite26ae3d5511b3b4c2a344a0af8235f68
{
    public static $prefixLengthsPsr4 = array (
        'i' => 
        array (
            'iio\\libmergepdf\\' => 16,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'iio\\libmergepdf\\' => 
        array (
            0 => __DIR__ . '/..' . '/iio/libmergepdf/src',
        ),
    );

    public static $classMap = array (
        'FPDF' => __DIR__ . '/..' . '/setasign/fpdf/fpdf.php',
        'FPDF_TPL' => __DIR__ . '/..' . '/setasign/fpdi/fpdf_tpl.php',
        'FPDI' => __DIR__ . '/..' . '/setasign/fpdi/fpdi.php',
        'FilterASCII85' => __DIR__ . '/..' . '/setasign/fpdi/filters/FilterASCII85.php',
        'FilterASCIIHexDecode' => __DIR__ . '/..' . '/setasign/fpdi/filters/FilterASCIIHexDecode.php',
        'FilterLZW' => __DIR__ . '/..' . '/setasign/fpdi/filters/FilterLZW.php',
        'fpdi_bridge' => __DIR__ . '/..' . '/setasign/fpdi-fpdf/fpdi_bridge.php',
        'fpdi_pdf_parser' => __DIR__ . '/..' . '/setasign/fpdi/fpdi_pdf_parser.php',
        'pdf_context' => __DIR__ . '/..' . '/setasign/fpdi/pdf_context.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInite26ae3d5511b3b4c2a344a0af8235f68::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInite26ae3d5511b3b4c2a344a0af8235f68::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInite26ae3d5511b3b4c2a344a0af8235f68::$classMap;

        }, null, ClassLoader::class);
    }
}
