<?php

use Phinx\Migration\AbstractMigration;

class InsertRechequeAnswers extends AbstractMigration
{
    /**
     * Change Method.
     *
     * Write your reversible migrations using this method.
     *
     * More information on writing migrations is available here:
     * https://book.cakephp.org/phinx/0/en/migrations.html
     *
     * The following commands can be used in this method and Phinx will
     * automatically reverse them when rolling back:
     *
     *    createTable
     *    renameTable
     *    addColumn
     *    addCustomColumn
     *    renameColumn
     *    addIndex
     *    addForeignKey
     *
     * Any other destructive changes will result in an error when trying to
     * rollback the migration.
     *
     * Remember to call "create()" or "update()" and NOT "save()" when working
     * with the Table class.
     */
    public function change()
    {
        $respostas = [
            [
                "respostaID" => 340,
                "produtoID" => 516,
                "respostaPaiID" => 0,
                "respostaRegistro" => "N500",
                "respostaSubtipo" => "00",
                "respostaNome" => "Score",
                "respostaAgruparColunas" => 2,
                "respostaQtdeColunas" => null,
                "respostaDataCancel" => "1901-01-01 00:00:00",
                "usuarioIDCancel" => null,
                "respostaVisivelCliente" => 1,
                "respostaFlagRestricao" => 2,
                "respostaNumeroOrdem" => 53,
                "respostaInformativo" => "",
            ],
            [
                "respostaID" => 339,
                "produtoID" => 516,
                "respostaPaiID" => 0,
                "respostaRegistro" => "N440",
                "respostaSubtipo" => "99",
                "respostaNome" => "Registros de Consultas",
                "respostaAgruparColunas" => 2,
                "respostaQtdeColunas" => 0,
                "respostaDataCancel" => "1901-01-01 00:00:00",
                "usuarioIDCancel" => null,
                "respostaVisivelCliente" => 1,
                "respostaFlagRestricao" => 2,
                "respostaNumeroOrdem" => 66,
                "respostaInformativo" => "",
            ],
            [
                "respostaID" => 338,
                "produtoID" => 516,
                "respostaPaiID" => 0,
                "respostaRegistro" => "N440",
                "respostaSubtipo" => "03",
                "respostaNome" => "Registro de Consultas Sem cheques",
                "respostaAgruparColunas" => 1,
                "respostaQtdeColunas" => 2,
                "respostaDataCancel" => "1901-01-01 00:00:00",
                "usuarioIDCancel" => null,
                "respostaVisivelCliente" => 1,
                "respostaFlagRestricao" => 2,
                "respostaNumeroOrdem" => 67,
                "respostaInformativo" => "",
            ],
            [
                "respostaID" => 337,
                "produtoID" => 516,
                "respostaPaiID" => 0,
                "respostaRegistro" => "N440",
                "respostaSubtipo" => "02",
                "respostaNome" => "Registro de Consultas – Referência Comercial",
                "respostaAgruparColunas" => 1,
                "respostaQtdeColunas" => 2,
                "respostaDataCancel" => "1901-01-01 00:00:00",
                "usuarioIDCancel" => null,
                "respostaVisivelCliente" => 1,
                "respostaFlagRestricao" => 2,
                "respostaNumeroOrdem" => 68,
                "respostaInformativo" => "",
            ],
            [
                "respostaID" => 336,
                "produtoID" => 516,
                "respostaPaiID" => 0,
                "respostaRegistro" => "N440",
                "respostaSubtipo" => "01",
                "respostaNome" => "Registro de Consultas de Cheques - Mercado",
                "respostaAgruparColunas" => 1,
                "respostaQtdeColunas" => 2,
                "respostaDataCancel" => "1901-01-01 00:00:00",
                "usuarioIDCancel" => null,
                "respostaVisivelCliente" => 1,
                "respostaFlagRestricao" => 2,
                "respostaNumeroOrdem" => 69,
                "respostaInformativo" => "",
            ],
            [
                "respostaID" => 335,
                "produtoID" => 516,
                "respostaPaiID" => 0,
                "respostaRegistro" => "N440",
                "respostaSubtipo" => "00",
                "respostaNome" => "Registro de Consultas de cheques - Interno",
                "respostaAgruparColunas" => 2,
                "respostaQtdeColunas" => 0,
                "respostaDataCancel" => "1901-01-01 00:00:00",
                "usuarioIDCancel" => null,
                "respostaVisivelCliente" => 2,
                "respostaFlagRestricao" => 2,
                "respostaNumeroOrdem" => 70,
                "respostaInformativo" => "",
            ],
            [
                "respostaID" => 334,
                "produtoID" => 516,
                "respostaPaiID" => 0,
                "respostaRegistro" => "N430",
                "respostaSubtipo" => "99",
                "respostaNome" => "Últimos Telefones Consultados",
                "respostaAgruparColunas" => 2,
                "respostaQtdeColunas" => 0,
                "respostaDataCancel" => "1901-01-01 00:00:00",
                "usuarioIDCancel" => null,
                "respostaVisivelCliente" => 1,
                "respostaFlagRestricao" => 2,
                "respostaNumeroOrdem" => 71,
                "respostaInformativo" => "",
            ],
            [
                "respostaID" => 333,
                "produtoID" => 516,
                "respostaPaiID" => 0,
                "respostaRegistro" => "N430",
                "respostaSubtipo" => "00",
                "respostaNome" => "Últimos telefones consultados",
                "respostaAgruparColunas" => 2,
                "respostaQtdeColunas" => 0,
                "respostaDataCancel" => "1901-01-01 00:00:00",
                "usuarioIDCancel" => null,
                "respostaVisivelCliente" => 1,
                "respostaFlagRestricao" => 2,
                "respostaNumeroOrdem" => 72,
                "respostaInformativo" => "",
            ],
            [
                "respostaID" => 332,
                "produtoID" => 516,
                "respostaPaiID" => 0,
                "respostaRegistro" => "N430",
                "respostaSubtipo" => "00",
                "respostaNome" => "Últimos Telefones Consultados",
                "respostaAgruparColunas" => 1,
                "respostaQtdeColunas" => 2,
                "respostaDataCancel" => "1901-01-01 00:00:00",
                "usuarioIDCancel" => null,
                "respostaVisivelCliente" => 1,
                "respostaFlagRestricao" => 2,
                "respostaNumeroOrdem" => 73,
                "respostaInformativo" => "",
            ],
            [
                "respostaID" => 331,
                "produtoID" => 516,
                "respostaPaiID" => 0,
                "respostaRegistro" => "N420",
                "respostaSubtipo" => "99",
                "respostaNome" => "Mensagem relativa ao Teleconfirma",
                "respostaAgruparColunas" => 2,
                "respostaQtdeColunas" => null,
                "respostaDataCancel" => "1901-01-01 00:00:00",
                "usuarioIDCancel" => null,
                "respostaVisivelCliente" => 1,
                "respostaFlagRestricao" => 2,
                "respostaNumeroOrdem" => 74,
                "respostaInformativo" => "",
            ],
            [
                "respostaID" => 330,
                "produtoID" => 516,
                "respostaPaiID" => 328,
                "respostaRegistro" => "N420",
                "respostaSubtipo" => "02",
                "respostaNome" => "Complemento endereço",
                "respostaAgruparColunas" => 2,
                "respostaQtdeColunas" => 0,
                "respostaDataCancel" => "1901-01-01 00:00:00",
                "usuarioIDCancel" => null,
                "respostaVisivelCliente" => 1,
                "respostaFlagRestricao" => 2,
                "respostaNumeroOrdem" => 65,
                "respostaInformativo" => "",
            ],
            [
                "respostaID" => 329,
                "produtoID" => 516,
                "respostaPaiID" => 328,
                "respostaRegistro" => "N420",
                "respostaSubtipo" => "01",
                "respostaNome" => "Endereço do Telefone",
                "respostaAgruparColunas" => 2,
                "respostaQtdeColunas" => 0,
                "respostaDataCancel" => "1901-01-01 00:00:00",
                "usuarioIDCancel" => null,
                "respostaVisivelCliente" => 1,
                "respostaFlagRestricao" => 2,
                "respostaNumeroOrdem" => 64,
                "respostaInformativo" => "",
            ],
            [
                "respostaID" => 328,
                "produtoID" => 516,
                "respostaPaiID" => 0,
                "respostaRegistro" => "N420",
                "respostaSubtipo" => "00",
                "respostaNome" => "Endereço Referente ao Telefone Consultado",
                "respostaAgruparColunas" => 1,
                "respostaQtdeColunas" => 2,
                "respostaDataCancel" => "1901-01-01 00:00:00",
                "usuarioIDCancel" => null,
                "respostaVisivelCliente" => 1,
                "respostaFlagRestricao" => 2,
                "respostaNumeroOrdem" => 63,
                "respostaInformativo" => "",
            ],
            [
                "respostaID" => 327,
                "produtoID" => 516,
                "respostaPaiID" => 0,
                "respostaRegistro" => "N410",
                "respostaSubtipo" => "99",
                "respostaNome" => "Caso o CEP não exista em nossas bases, retornará somente este registro com a mensagem explicativa",
                "respostaAgruparColunas" => 2,
                "respostaQtdeColunas" => null,
                "respostaDataCancel" => "1901-01-01 00:00:00",
                "usuarioIDCancel" => null,
                "respostaVisivelCliente" => 1,
                "respostaFlagRestricao" => 2,
                "respostaNumeroOrdem" => 54,
                "respostaInformativo" => "",
            ],
            [
                "respostaID" => 326,
                "produtoID" => 516,
                "respostaPaiID" => 0,
                "respostaRegistro" => "N410",
                "respostaSubtipo" => "01",
                "respostaNome" => "Complemento",
                "respostaAgruparColunas" => 2,
                "respostaQtdeColunas" => null,
                "respostaDataCancel" => "1901-01-01 00:00:00",
                "usuarioIDCancel" => null,
                "respostaVisivelCliente" => 1,
                "respostaFlagRestricao" => 2,
                "respostaNumeroOrdem" => 55,
                "respostaInformativo" => "",
            ],
            [
                "respostaID" => 325,
                "produtoID" => 516,
                "respostaPaiID" => 0,
                "respostaRegistro" => "N410",
                "respostaSubtipo" => "00",
                "respostaNome" => "Endereço do CEP",
                "respostaAgruparColunas" => 2,
                "respostaQtdeColunas" => null,
                "respostaDataCancel" => "1901-01-01 00:00:00",
                "usuarioIDCancel" => null,
                "respostaVisivelCliente" => 1,
                "respostaFlagRestricao" => 2,
                "respostaNumeroOrdem" => 56,
                "respostaInformativo" => "",
            ],
            [
                "respostaID" => 324,
                "produtoID" => 516,
                "respostaPaiID" => 0,
                "respostaRegistro" => "N400",
                "respostaSubtipo" => "99",
                "respostaNome" => "Agência Bancária",
                "respostaAgruparColunas" => 2,
                "respostaQtdeColunas" => 0,
                "respostaDataCancel" => "1901-01-01 00:00:00",
                "usuarioIDCancel" => null,
                "respostaVisivelCliente" => 1,
                "respostaFlagRestricao" => 2,
                "respostaNumeroOrdem" => 57,
                "respostaInformativo" => "",
            ],
            [
                "respostaID" => 323,
                "produtoID" => 516,
                "respostaPaiID" => 293,
                "respostaRegistro" => "N400",
                "respostaSubtipo" => "01",
                "respostaNome" => "Detalhes da Agência Bancária - Complemento",
                "respostaAgruparColunas" => 1,
                "respostaQtdeColunas" => 2,
                "respostaDataCancel" => "1901-01-01 00:00:00",
                "usuarioIDCancel" => null,
                "respostaVisivelCliente" => 1,
                "respostaFlagRestricao" => 2,
                "respostaNumeroOrdem" => 58,
                "respostaInformativo" => "",
            ],
            [
                "respostaID" => 322,
                "produtoID" => 516,
                "respostaPaiID" => 0,
                "respostaRegistro" => "N400",
                "respostaSubtipo" => "00",
                "respostaNome" => "Detalhes da Agência Bancária ",
                "respostaAgruparColunas" => 2,
                "respostaQtdeColunas" => 0,
                "respostaDataCancel" => "1901-01-01 00:00:00",
                "usuarioIDCancel" => null,
                "respostaVisivelCliente" => 1,
                "respostaFlagRestricao" => 2,
                "respostaNumeroOrdem" => 59,
                "respostaInformativo" => "",
            ],
            [
                "respostaID" => 321,
                "produtoID" => 516,
                "respostaPaiID" => 0,
                "respostaRegistro" => "N400",
                "respostaSubtipo" => "00",
                "respostaNome" => "Detalhes da Agência Bancária (com campo DDD com 4 posições e telefone com 10 posições)",
                "respostaAgruparColunas" => 2,
                "respostaQtdeColunas" => null,
                "respostaDataCancel" => "2013-08-14 14:29:28",
                "usuarioIDCancel" => 1,
                "respostaVisivelCliente" => 1,
                "respostaFlagRestricao" => 2,
                "respostaNumeroOrdem" => 60,
                "respostaInformativo" => "",
            ],
            [
                "respostaID" => 295,
                "produtoID" => 516,
                "respostaPaiID" => 0,
                "respostaRegistro" => "N400",
                "respostaSubtipo" => "99",
                "respostaNome" => "Caso a agência bancária não exista em nossas bases, retornará somente este registro com a mensagem explicativa",
                "respostaAgruparColunas" => 2,
                "respostaQtdeColunas" => null,
                "respostaDataCancel" => "2013-08-14 14:29:48",
                "usuarioIDCancel" => 1,
                "respostaVisivelCliente" => 1,
                "respostaFlagRestricao" => 2,
                "respostaNumeroOrdem" => 61,
                "respostaInformativo" => "",
            ],
            [
                "respostaID" => 294,
                "produtoID" => 516,
                "respostaPaiID" => 0,
                "respostaRegistro" => "N400",
                "respostaSubtipo" => "01",
                "respostaNome" => "Detalhes da Agência Bancária - Complemento",
                "respostaAgruparColunas" => 2,
                "respostaQtdeColunas" => null,
                "respostaDataCancel" => "2013-08-14 14:29:37",
                "usuarioIDCancel" => 1,
                "respostaVisivelCliente" => 1,
                "respostaFlagRestricao" => 2,
                "respostaNumeroOrdem" => 62,
                "respostaInformativo" => "",
            ],
            [
                "respostaID" => 293,
                "produtoID" => 516,
                "respostaPaiID" => 0,
                "respostaRegistro" => "N400",
                "respostaSubtipo" => "00",
                "respostaNome" => "Agência Bancária",
                "respostaAgruparColunas" => 1,
                "respostaQtdeColunas" => 3,
                "respostaDataCancel" => "1901-01-01 00:00:00",
                "usuarioIDCancel" => null,
                "respostaVisivelCliente" => 1,
                "respostaFlagRestricao" => 2,
                "respostaNumeroOrdem" => 5,
                "respostaInformativo" => "",
            ],
            [
                "respostaID" => 292,
                "produtoID" => 516,
                "respostaPaiID" => 0,
                "respostaRegistro" => "N330",
                "respostaSubtipo" => "99",
                "respostaNome" => "Caso o documento consultado não possua registros de consulta para os dados informados, retornará somente este registro com a mensagem explicativa",
                "respostaAgruparColunas" => 2,
                "respostaQtdeColunas" => null,
                "respostaDataCancel" => "1901-01-01 00:00:00",
                "usuarioIDCancel" => null,
                "respostaVisivelCliente" => 1,
                "respostaFlagRestricao" => 2,
                "respostaNumeroOrdem" => 75,
                "respostaInformativo" => "",
            ],
            [
                "respostaID" => 291,
                "produtoID" => 516,
                "respostaPaiID" => 0,
                "respostaRegistro" => "N330",
                "respostaSubtipo" => "02",
                "respostaNome" => "Histórico de Conta Corrente",
                "respostaAgruparColunas" => 2,
                "respostaQtdeColunas" => null,
                "respostaDataCancel" => "1901-01-01 00:00:00",
                "usuarioIDCancel" => null,
                "respostaVisivelCliente" => 1,
                "respostaFlagRestricao" => 2,
                "respostaNumeroOrdem" => 76,
                "respostaInformativo" => "",
            ],
            [
                "respostaID" => 290,
                "produtoID" => 516,
                "respostaPaiID" => 0,
                "respostaRegistro" => "N330",
                "respostaSubtipo" => "01",
                "respostaNome" => "Segunda verificação",
                "respostaAgruparColunas" => 2,
                "respostaQtdeColunas" => null,
                "respostaDataCancel" => "1901-01-01 00:00:00",
                "usuarioIDCancel" => null,
                "respostaVisivelCliente" => 1,
                "respostaFlagRestricao" => 2,
                "respostaNumeroOrdem" => 87,
                "respostaInformativo" => "",
            ],
            [
                "respostaID" => 289,
                "produtoID" => 516,
                "respostaPaiID" => 0,
                "respostaRegistro" => "N330",
                "respostaSubtipo" => "00",
                "respostaNome" => "Primeira verificação",
                "respostaAgruparColunas" => 2,
                "respostaQtdeColunas" => null,
                "respostaDataCancel" => "1901-01-01 00:00:00",
                "usuarioIDCancel" => null,
                "respostaVisivelCliente" => 1,
                "respostaFlagRestricao" => 2,
                "respostaNumeroOrdem" => 88,
                "respostaInformativo" => "",
            ],
            [
                "respostaID" => 288,
                "produtoID" => 516,
                "respostaPaiID" => 0,
                "respostaRegistro" => "N320",
                "respostaSubtipo" => "99",
                "respostaNome" => "Detalhe de Cheque Sustado, Extraviado ou Cancelado",
                "respostaAgruparColunas" => 2,
                "respostaQtdeColunas" => 0,
                "respostaDataCancel" => "1901-01-01 00:00:00",
                "usuarioIDCancel" => null,
                "respostaVisivelCliente" => 2,
                "respostaFlagRestricao" => 2,
                "respostaNumeroOrdem" => 89,
                "respostaInformativo" => "",
            ],
            [
                "respostaID" => 287,
                "produtoID" => 516,
                "respostaPaiID" => 0,
                "respostaRegistro" => "N320",
                "respostaSubtipo" => "90",
                "respostaNome" => "Totais de Contumácia",
                "respostaAgruparColunas" => 2,
                "respostaQtdeColunas" => 0,
                "respostaDataCancel" => "1901-01-01 00:00:00",
                "usuarioIDCancel" => null,
                "respostaVisivelCliente" => 2,
                "respostaFlagRestricao" => 2,
                "respostaNumeroOrdem" => 90,
                "respostaInformativo" => "",
            ],
            [
                "respostaID" => 286,
                "produtoID" => 516,
                "respostaPaiID" => 0,
                "respostaRegistro" => "N320",
                "respostaSubtipo" => "00",
                "respostaNome" => "Detalhes de Contumácia",
                "respostaAgruparColunas" => 2,
                "respostaQtdeColunas" => 0,
                "respostaDataCancel" => "1901-01-01 00:00:00",
                "usuarioIDCancel" => null,
                "respostaVisivelCliente" => 2,
                "respostaFlagRestricao" => 2,
                "respostaNumeroOrdem" => 91,
                "respostaInformativo" => "",
            ],
            [
                "respostaID" => 284,
                "produtoID" => 516,
                "respostaPaiID" => 0,
                "respostaRegistro" => "N310",
                "respostaSubtipo" => "00",
                "respostaNome" => "Detalhes de Cheque Sustado, Extraviado, Cancelado, Roubado e Bloqueado",
                "respostaAgruparColunas" => 1,
                "respostaQtdeColunas" => 3,
                "respostaDataCancel" => "1901-01-01 00:00:00",
                "usuarioIDCancel" => null,
                "respostaVisivelCliente" => 1,
                "respostaFlagRestricao" => 2,
                "respostaNumeroOrdem" => 4,
                "respostaInformativo" => "",
            ],
            [
                "respostaID" => 285,
                "produtoID" => 516,
                "respostaPaiID" => 0,
                "respostaRegistro" => "N310",
                "respostaSubtipo" => "99",
                "respostaNome" => "DETALHE DE CHEQUES SUSTADO, EXTRAVIADO, CANCELADO, ROUBADO E BLOQUEADO",
                "respostaAgruparColunas" => 2,
                "respostaQtdeColunas" => 0,
                "respostaDataCancel" => "1901-01-01 00:00:00",
                "usuarioIDCancel" => null,
                "respostaVisivelCliente" => 1,
                "respostaFlagRestricao" => 2,
                "respostaNumeroOrdem" => 6,
                "respostaInformativo" => "",
            ],
            [
                "respostaID" => 282,
                "produtoID" => 516,
                "respostaPaiID" => 0,
                "respostaRegistro" => "N300",
                "respostaSubtipo" => "01",
                "respostaNome" => "Complemento",
                "respostaAgruparColunas" => 2,
                "respostaQtdeColunas" => null,
                "respostaDataCancel" => "1901-01-01 00:00:00",
                "usuarioIDCancel" => null,
                "respostaVisivelCliente" => 1,
                "respostaFlagRestricao" => 2,
                "respostaNumeroOrdem" => 92,
                "respostaInformativo" => "",
            ],
            [
                "respostaID" => 283,
                "produtoID" => 516,
                "respostaPaiID" => 0,
                "respostaRegistro" => "N300",
                "respostaSubtipo" => "99",
                "respostaNome" => "Caso ocorram inconsistências ou o acesso ao banco não estiver disponível, retornará somente este registro com a mensagem explicativa",
                "respostaAgruparColunas" => 2,
                "respostaQtdeColunas" => null,
                "respostaDataCancel" => "1901-01-01 00:00:00",
                "usuarioIDCancel" => null,
                "respostaVisivelCliente" => 1,
                "respostaFlagRestricao" => 2,
                "respostaNumeroOrdem" => 93,
                "respostaInformativo" => "",
            ],
            [
                "respostaID" => 281,
                "produtoID" => 516,
                "respostaPaiID" => 0,
                "respostaRegistro" => "N300",
                "respostaSubtipo" => "00",
                "respostaNome" => "Informações relativas a conta corrente e correntista",
                "respostaAgruparColunas" => 2,
                "respostaQtdeColunas" => null,
                "respostaDataCancel" => "1901-01-01 00:00:00",
                "usuarioIDCancel" => null,
                "respostaVisivelCliente" => 1,
                "respostaFlagRestricao" => 2,
                "respostaNumeroOrdem" => 86,
                "respostaInformativo" => "",
            ],
            [
                "respostaID" => 280,
                "produtoID" => 516,
                "respostaPaiID" => 0,
                "respostaRegistro" => "N270",
                "respostaSubtipo" => "99",
                "respostaNome" => "Resumo de Cheque Sem Fundos",
                "respostaAgruparColunas" => 2,
                "respostaQtdeColunas" => 0,
                "respostaDataCancel" => "1901-01-01 00:00:00",
                "usuarioIDCancel" => null,
                "respostaVisivelCliente" => 1,
                "respostaFlagRestricao" => 2,
                "respostaNumeroOrdem" => 3,
                "respostaInformativo" => "",
            ],
            [
                "respostaID" => 278,
                "produtoID" => 516,
                "respostaPaiID" => 0,
                "respostaRegistro" => "N270",
                "respostaSubtipo" => "00",
                "respostaNome" => "Detalhe de Cheques Sem Fundos",
                "respostaAgruparColunas" => 1,
                "respostaQtdeColunas" => 2,
                "respostaDataCancel" => "1901-01-01 00:00:00",
                "usuarioIDCancel" => null,
                "respostaVisivelCliente" => 2,
                "respostaFlagRestricao" => 2,
                "respostaNumeroOrdem" => 85,
                "respostaInformativo" => "",
            ],
            [
                "respostaID" => 279,
                "produtoID" => 516,
                "respostaPaiID" => 0,
                "respostaRegistro" => "N270",
                "respostaSubtipo" => "90",
                "respostaNome" => "Resumo de Cheque Sem Fundos",
                "respostaAgruparColunas" => 1,
                "respostaQtdeColunas" => 3,
                "respostaDataCancel" => "1901-01-01 00:00:00",
                "usuarioIDCancel" => null,
                "respostaVisivelCliente" => 1,
                "respostaFlagRestricao" => 2,
                "respostaNumeroOrdem" => 2,
                "respostaInformativo" => "",
            ],
            [
                "respostaID" => 277,
                "produtoID" => 516,
                "respostaPaiID" => 0,
                "respostaRegistro" => "N250",
                "respostaSubtipo" => "99",
                "respostaNome" => "Caso não existam Protestos do Estado, retornará somente este registro com a mensagem explicativa",
                "respostaAgruparColunas" => 2,
                "respostaQtdeColunas" => 0,
                "respostaDataCancel" => "1901-01-01 00:00:00",
                "usuarioIDCancel" => null,
                "respostaVisivelCliente" => 1,
                "respostaFlagRestricao" => 1,
                "respostaNumeroOrdem" => 77,
                "respostaInformativo" => "",
            ],
            [
                "respostaID" => 276,
                "produtoID" => 516,
                "respostaPaiID" => 0,
                "respostaRegistro" => "N250",
                "respostaSubtipo" => "90",
                "respostaNome" => "Total de Protestos do Estado",
                "respostaAgruparColunas" => 2,
                "respostaQtdeColunas" => null,
                "respostaDataCancel" => "1901-01-01 00:00:00",
                "usuarioIDCancel" => null,
                "respostaVisivelCliente" => 1,
                "respostaFlagRestricao" => 2,
                "respostaNumeroOrdem" => 78,
                "respostaInformativo" => "",
            ],
            [
                "respostaID" => 275,
                "produtoID" => 516,
                "respostaPaiID" => 0,
                "respostaRegistro" => "N250",
                "respostaSubtipo" => "01",
                "respostaNome" => "Detalhe de Protestos do Estado – complemento",
                "respostaAgruparColunas" => 2,
                "respostaQtdeColunas" => 0,
                "respostaDataCancel" => "1901-01-01 00:00:00",
                "usuarioIDCancel" => null,
                "respostaVisivelCliente" => 1,
                "respostaFlagRestricao" => 1,
                "respostaNumeroOrdem" => 79,
                "respostaInformativo" => "",
            ],
            [
                "respostaID" => 274,
                "produtoID" => 516,
                "respostaPaiID" => 0,
                "respostaRegistro" => "N250",
                "respostaSubtipo" => "00",
                "respostaNome" => "Detalhe dos Protestos do Estado",
                "respostaAgruparColunas" => 2,
                "respostaQtdeColunas" => null,
                "respostaDataCancel" => "1901-01-01 00:00:00",
                "usuarioIDCancel" => null,
                "respostaVisivelCliente" => 1,
                "respostaFlagRestricao" => 2,
                "respostaNumeroOrdem" => 80,
                "respostaInformativo" => "",
            ],
            [
                "respostaID" => 273,
                "produtoID" => 516,
                "respostaPaiID" => 0,
                "respostaRegistro" => "N240",
                "respostaSubtipo" => "99",
                "respostaNome" => "Pendências Financeiras",
                "respostaAgruparColunas" => 2,
                "respostaQtdeColunas" => 0,
                "respostaDataCancel" => "1901-01-01 00:00:00",
                "usuarioIDCancel" => null,
                "respostaVisivelCliente" => 1,
                "respostaFlagRestricao" => 2,
                "respostaNumeroOrdem" => 81,
                "respostaInformativo" => "",
            ],
            [
                "respostaID" => 272,
                "produtoID" => 516,
                "respostaPaiID" => 0,
                "respostaRegistro" => "N240",
                "respostaSubtipo" => "90",
                "respostaNome" => "Total de Pendências Financeiras para cada tipo de anotação (“V” = Pefin / “I” = Refin / “5” = Dívida Vencida)",
                "respostaAgruparColunas" => 2,
                "respostaQtdeColunas" => null,
                "respostaDataCancel" => "2013-08-13 16:28:03",
                "usuarioIDCancel" => 1,
                "respostaVisivelCliente" => 1,
                "respostaFlagRestricao" => 2,
                "respostaNumeroOrdem" => 82,
                "respostaInformativo" => "",
            ],
            [
                "respostaID" => 271,
                "produtoID" => 516,
                "respostaPaiID" => 0,
                "respostaRegistro" => "N240",
                "respostaSubtipo" => "90",
                "respostaNome" => "Total de Pendências Financeiras para cada tipo de anotação (“V” = Pefin / “I” = Refin / “5” = Dívida Vencida)",
                "respostaAgruparColunas" => 2,
                "respostaQtdeColunas" => 0,
                "respostaDataCancel" => "1901-01-01 00:00:00",
                "usuarioIDCancel" => null,
                "respostaVisivelCliente" => 1,
                "respostaFlagRestricao" => 1,
                "respostaNumeroOrdem" => 83,
                "respostaInformativo" => "",
            ],
            [
                "respostaID" => 269,
                "produtoID" => 516,
                "respostaPaiID" => 0,
                "respostaRegistro" => "N240",
                "respostaSubtipo" => "00",
                "respostaNome" => "Detalhe das Pendências Financeiras separadas em Pefin, Refin e Dívidas vencidas",
                "respostaAgruparColunas" => 2,
                "respostaQtdeColunas" => 0,
                "respostaDataCancel" => "1901-01-01 00:00:00",
                "usuarioIDCancel" => null,
                "respostaVisivelCliente" => 1,
                "respostaFlagRestricao" => 1,
                "respostaNumeroOrdem" => 84,
                "respostaInformativo" => "",
            ],
            [
                "respostaID" => 270,
                "produtoID" => 516,
                "respostaPaiID" => 0,
                "respostaRegistro" => "N240",
                "respostaSubtipo" => "01",
                "respostaNome" => "Detalhe de Pendências Financeiras – complemento",
                "respostaAgruparColunas" => 2,
                "respostaQtdeColunas" => 0,
                "respostaDataCancel" => "1901-01-01 00:00:00",
                "usuarioIDCancel" => null,
                "respostaVisivelCliente" => 1,
                "respostaFlagRestricao" => 1,
                "respostaNumeroOrdem" => 94,
                "respostaInformativo" => "",
            ],
            [
                "respostaID" => 268,
                "produtoID" => 516,
                "respostaPaiID" => 0,
                "respostaRegistro" => "N230",
                "respostaSubtipo" => "99",
                "respostaNome" => "Pendências Internas",
                "respostaAgruparColunas" => 2,
                "respostaQtdeColunas" => 0,
                "respostaDataCancel" => "1901-01-01 00:00:00",
                "usuarioIDCancel" => null,
                "respostaVisivelCliente" => 1,
                "respostaFlagRestricao" => 2,
                "respostaNumeroOrdem" => 8,
                "respostaInformativo" => "",
            ],
            [
                "respostaID" => 266,
                "produtoID" => 516,
                "respostaPaiID" => 0,
                "respostaRegistro" => "N230",
                "respostaSubtipo" => "00",
                "respostaNome" => "Detalhe de Pendências Internas",
                "respostaAgruparColunas" => 2,
                "respostaQtdeColunas" => 0,
                "respostaDataCancel" => "1901-01-01 00:00:00",
                "usuarioIDCancel" => null,
                "respostaVisivelCliente" => 1,
                "respostaFlagRestricao" => 1,
                "respostaNumeroOrdem" => 21,
                "respostaInformativo" => "",
            ],
            [
                "respostaID" => 267,
                "produtoID" => 516,
                "respostaPaiID" => 0,
                "respostaRegistro" => "N230",
                "respostaSubtipo" => "90",
                "respostaNome" => "Total de Pendências Internas",
                "respostaAgruparColunas" => 2,
                "respostaQtdeColunas" => 0,
                "respostaDataCancel" => "1901-01-01 00:00:00",
                "usuarioIDCancel" => null,
                "respostaVisivelCliente" => 1,
                "respostaFlagRestricao" => 1,
                "respostaNumeroOrdem" => 22,
                "respostaInformativo" => "",
            ],
            [
                "respostaID" => 265,
                "produtoID" => 516,
                "respostaPaiID" => 0,
                "respostaRegistro" => "N220",
                "respostaSubtipo" => "00",
                "respostaNome" => "Nada Consta",
                "respostaAgruparColunas" => 2,
                "respostaQtdeColunas" => null,
                "respostaDataCancel" => "1901-01-01 00:00:00",
                "usuarioIDCancel" => null,
                "respostaVisivelCliente" => 1,
                "respostaFlagRestricao" => 2,
                "respostaNumeroOrdem" => 23,
                "respostaInformativo" => "",
            ],
            [
                "respostaID" => 264,
                "produtoID" => 516,
                "respostaPaiID" => 0,
                "respostaRegistro" => "N210",
                "respostaSubtipo" => "99",
                "respostaNome" => "Documentos Roubados, Furtados ou Extraviados",
                "respostaAgruparColunas" => 2,
                "respostaQtdeColunas" => 0,
                "respostaDataCancel" => "1901-01-01 00:00:00",
                "usuarioIDCancel" => null,
                "respostaVisivelCliente" => 1,
                "respostaFlagRestricao" => 2,
                "respostaNumeroOrdem" => 7,
                "respostaInformativo" => "",
            ],
            [
                "respostaID" => 263,
                "produtoID" => 516,
                "respostaPaiID" => 0,
                "respostaRegistro" => "N210",
                "respostaSubtipo" => "01",
                "respostaNome" => "N210 com campo DDD com 4 posições e telefone com 10 posições.",
                "respostaAgruparColunas" => 2,
                "respostaQtdeColunas" => null,
                "respostaDataCancel" => "1901-01-01 00:00:00",
                "usuarioIDCancel" => null,
                "respostaVisivelCliente" => 1,
                "respostaFlagRestricao" => 2,
                "respostaNumeroOrdem" => 24,
                "respostaInformativo" => "",
            ],
            [
                "respostaID" => 262,
                "produtoID" => 516,
                "respostaPaiID" => 0,
                "respostaRegistro" => "N210",
                "respostaSubtipo" => "01",
                "respostaNome" => "Informações de DDD/telefones ref. documentos roubados",
                "respostaAgruparColunas" => 2,
                "respostaQtdeColunas" => null,
                "respostaDataCancel" => "1901-01-01 00:00:00",
                "usuarioIDCancel" => null,
                "respostaVisivelCliente" => 1,
                "respostaFlagRestricao" => 2,
                "respostaNumeroOrdem" => 25,
                "respostaInformativo" => "",
            ],
            [
                "respostaID" => 260,
                "produtoID" => 516,
                "respostaPaiID" => 259,
                "respostaRegistro" => "N200",
                "respostaSubtipo" => "01",
                "respostaNome" => "Complemento do Bloco Confirmei",
                "respostaAgruparColunas" => 2,
                "respostaQtdeColunas" => 0,
                "respostaDataCancel" => "1901-01-01 00:00:00",
                "usuarioIDCancel" => null,
                "respostaVisivelCliente" => 1,
                "respostaFlagRestricao" => 2,
                "respostaNumeroOrdem" => 26,
                "respostaInformativo" => "",
            ],
            [
                "respostaID" => 261,
                "produtoID" => 516,
                "respostaPaiID" => 0,
                "respostaRegistro" => "N210",
                "respostaSubtipo" => "00",
                "respostaNome" => "Mensagens de documentos Roubados",
                "respostaAgruparColunas" => 2,
                "respostaQtdeColunas" => null,
                "respostaDataCancel" => "1901-01-01 00:00:00",
                "usuarioIDCancel" => null,
                "respostaVisivelCliente" => 1,
                "respostaFlagRestricao" => 2,
                "respostaNumeroOrdem" => 27,
                "respostaInformativo" => "",
            ],
            [
                "respostaID" => 259,
                "produtoID" => 516,
                "respostaPaiID" => 0,
                "respostaRegistro" => "N200",
                "respostaSubtipo" => "00",
                "respostaNome" => "Identificação",
                "respostaAgruparColunas" => 1,
                "respostaQtdeColunas" => 2,
                "respostaDataCancel" => "1901-01-01 00:00:00",
                "usuarioIDCancel" => null,
                "respostaVisivelCliente" => 1,
                "respostaFlagRestricao" => 2,
                "respostaNumeroOrdem" => 1,
                "respostaInformativo" => "",
            ],
            [
                "respostaID" => 1,
                "produtoID" => 516,
                "respostaPaiID" => 0,
                "respostaRegistro" => "010",
                "respostaSubtipo" => "01",
                "respostaNome" => "Identificação do veículo – BIN Est/Fed",
                "respostaAgruparColunas" => 2,
                "respostaQtdeColunas" => null,
                "respostaDataCancel" => "2013-08-13 14:49:04",
                "usuarioIDCancel" => 1,
                "respostaVisivelCliente" => 1,
                "respostaFlagRestricao" => 2,
                "respostaNumeroOrdem" => 20,
                "respostaInformativo" => "",
            ],
            [
                "respostaID" => 341,
                "produtoID" => 516,
                "respostaPaiID" => 0,
                "respostaRegistro" => "N600",
                "respostaSubtipo" => "00",
                "respostaNome" => "Limite de Crédito / Cheques",
                "respostaAgruparColunas" => 2,
                "respostaQtdeColunas" => null,
                "respostaDataCancel" => "1901-01-01 00:00:00",
                "usuarioIDCancel" => null,
                "respostaVisivelCliente" => 1,
                "respostaFlagRestricao" => 2,
                "respostaNumeroOrdem" => 19,
                "respostaInformativo" => "",
            ],
            [
                "respostaID" => 342,
                "produtoID" => 516,
                "respostaPaiID" => 0,
                "respostaRegistro" => "N600",
                "respostaSubtipo" => "01",
                "respostaNome" => "Cheques – Pode ocorrer diversas vezes",
                "respostaAgruparColunas" => 2,
                "respostaQtdeColunas" => 0,
                "respostaDataCancel" => "1901-01-01 00:00:00",
                "usuarioIDCancel" => null,
                "respostaVisivelCliente" => 1,
                "respostaFlagRestricao" => 1,
                "respostaNumeroOrdem" => 18,
                "respostaInformativo" => "",
            ],
            [
                "respostaID" => 343,
                "produtoID" => 516,
                "respostaPaiID" => 0,
                "respostaRegistro" => "N600",
                "respostaSubtipo" => "02",
                "respostaNome" => "Subtotais",
                "respostaAgruparColunas" => 2,
                "respostaQtdeColunas" => null,
                "respostaDataCancel" => "1901-01-01 00:00:00",
                "usuarioIDCancel" => null,
                "respostaVisivelCliente" => 1,
                "respostaFlagRestricao" => 2,
                "respostaNumeroOrdem" => 9,
                "respostaInformativo" => "",
            ],
            [
                "respostaID" => 344,
                "produtoID" => 516,
                "respostaPaiID" => 0,
                "respostaRegistro" => "N600",
                "respostaSubtipo" => "03",
                "respostaNome" => "Totais a vencer",
                "respostaAgruparColunas" => 2,
                "respostaQtdeColunas" => null,
                "respostaDataCancel" => "1901-01-01 00:00:00",
                "usuarioIDCancel" => null,
                "respostaVisivelCliente" => 1,
                "respostaFlagRestricao" => 2,
                "respostaNumeroOrdem" => 10,
                "respostaInformativo" => "",
            ],
            [
                "respostaID" => 345,
                "produtoID" => 516,
                "respostaPaiID" => 0,
                "respostaRegistro" => "N600",
                "respostaSubtipo" => "04",
                "respostaNome" => "Totais a vista",
                "respostaAgruparColunas" => 2,
                "respostaQtdeColunas" => null,
                "respostaDataCancel" => "1901-01-01 00:00:00",
                "usuarioIDCancel" => null,
                "respostaVisivelCliente" => 1,
                "respostaFlagRestricao" => 2,
                "respostaNumeroOrdem" => 11,
                "respostaInformativo" => "",
            ],
            [
                "respostaID" => 346,
                "produtoID" => 516,
                "respostaPaiID" => 0,
                "respostaRegistro" => "N600",
                "respostaSubtipo" => "05",
                "respostaNome" => "Totais a prazo",
                "respostaAgruparColunas" => 2,
                "respostaQtdeColunas" => null,
                "respostaDataCancel" => "1901-01-01 00:00:00",
                "usuarioIDCancel" => null,
                "respostaVisivelCliente" => 1,
                "respostaFlagRestricao" => 2,
                "respostaNumeroOrdem" => 12,
                "respostaInformativo" => "",
            ],
            [
                "respostaID" => 347,
                "produtoID" => 516,
                "respostaPaiID" => 0,
                "respostaRegistro" => "N610",
                "respostaSubtipo" => "00",
                "respostaNome" => "Concentre Scoring PJ",
                "respostaAgruparColunas" => 2,
                "respostaQtdeColunas" => null,
                "respostaDataCancel" => "1901-01-01 00:00:00",
                "usuarioIDCancel" => null,
                "respostaVisivelCliente" => 1,
                "respostaFlagRestricao" => 2,
                "respostaNumeroOrdem" => 13,
                "respostaInformativo" => "",
            ],
            [
                "respostaID" => 348,
                "produtoID" => 516,
                "respostaPaiID" => 0,
                "respostaRegistro" => "N610",
                "respostaSubtipo" => "99",
                "respostaNome" => "Caso o score não seja calculado",
                "respostaAgruparColunas" => 2,
                "respostaQtdeColunas" => null,
                "respostaDataCancel" => "1901-01-01 00:00:00",
                "usuarioIDCancel" => null,
                "respostaVisivelCliente" => 1,
                "respostaFlagRestricao" => 2,
                "respostaNumeroOrdem" => 14,
                "respostaInformativo" => "",
            ],
            [
                "respostaID" => 349,
                "produtoID" => 516,
                "respostaPaiID" => 0,
                "respostaRegistro" => "N620",
                "respostaSubtipo" => "00",
                "respostaNome" => "Limite de Crédito PJ",
                "respostaAgruparColunas" => 2,
                "respostaQtdeColunas" => null,
                "respostaDataCancel" => "1901-01-01 00:00:00",
                "usuarioIDCancel" => null,
                "respostaVisivelCliente" => 1,
                "respostaFlagRestricao" => 2,
                "respostaNumeroOrdem" => 15,
                "respostaInformativo" => "",
            ],
            [
                "respostaID" => 350,
                "produtoID" => 516,
                "respostaPaiID" => 0,
                "respostaRegistro" => "N620",
                "respostaSubtipo" => "90",
                "respostaNome" => "Mensagem informativa do cálculo do limite. Este registro poderá ocorrer até 10 vezes",
                "respostaAgruparColunas" => 2,
                "respostaQtdeColunas" => null,
                "respostaDataCancel" => "1901-01-01 00:00:00",
                "usuarioIDCancel" => null,
                "respostaVisivelCliente" => 1,
                "respostaFlagRestricao" => 2,
                "respostaNumeroOrdem" => 16,
                "respostaInformativo" => "",
            ],
            [
                "respostaID" => 351,
                "produtoID" => 516,
                "respostaPaiID" => 0,
                "respostaRegistro" => "N620",
                "respostaSubtipo" => "99",
                "respostaNome" => "Mensagem informativa caso o limite não seja calculado. Este registro poderá ocorrer até 10 vezes",
                "respostaAgruparColunas" => 2,
                "respostaQtdeColunas" => null,
                "respostaDataCancel" => "1901-01-01 00:00:00",
                "usuarioIDCancel" => null,
                "respostaVisivelCliente" => 1,
                "respostaFlagRestricao" => 2,
                "respostaNumeroOrdem" => 17,
                "respostaInformativo" => "",
            ],
            [
                "respostaID" => 352,
                "produtoID" => 516,
                "respostaPaiID" => 0,
                "respostaRegistro" => "N630",
                "respostaSubtipo" => "00",
                "respostaNome" => "AlertaScoring PJ",
                "respostaAgruparColunas" => 2,
                "respostaQtdeColunas" => null,
                "respostaDataCancel" => "1901-01-01 00:00:00",
                "usuarioIDCancel" => null,
                "respostaVisivelCliente" => 1,
                "respostaFlagRestricao" => 2,
                "respostaNumeroOrdem" => 28,
                "respostaInformativo" => "",
            ],
            [
                "respostaID" => 353,
                "produtoID" => 516,
                "respostaPaiID" => 0,
                "respostaRegistro" => "N630",
                "respostaSubtipo" => "99",
                "respostaNome" => "Caso o alerta não seja calculado",
                "respostaAgruparColunas" => 2,
                "respostaQtdeColunas" => null,
                "respostaDataCancel" => "1901-01-01 00:00:00",
                "usuarioIDCancel" => null,
                "respostaVisivelCliente" => 1,
                "respostaFlagRestricao" => 2,
                "respostaNumeroOrdem" => 29,
                "respostaInformativo" => "",
            ],
            [
                "respostaID" => 354,
                "produtoID" => 516,
                "respostaPaiID" => 0,
                "respostaRegistro" => "N640",
                "respostaSubtipo" => "00",
                "respostaNome" => "Faturamento Presumido PJ",
                "respostaAgruparColunas" => 2,
                "respostaQtdeColunas" => null,
                "respostaDataCancel" => "1901-01-01 00:00:00",
                "usuarioIDCancel" => null,
                "respostaVisivelCliente" => 1,
                "respostaFlagRestricao" => 2,
                "respostaNumeroOrdem" => 30,
                "respostaInformativo" => "",
            ],
            [
                "respostaID" => 355,
                "produtoID" => 516,
                "respostaPaiID" => 0,
                "respostaRegistro" => "N640",
                "respostaSubtipo" => "90",
                "respostaNome" => "Mensagem relativa ao cálculo do Faturamento. Este registro poderá ocorrer até 10 vezes",
                "respostaAgruparColunas" => 2,
                "respostaQtdeColunas" => null,
                "respostaDataCancel" => "1901-01-01 00:00:00",
                "usuarioIDCancel" => null,
                "respostaVisivelCliente" => 1,
                "respostaFlagRestricao" => 2,
                "respostaNumeroOrdem" => 43,
                "respostaInformativo" => "",
            ],
            [
                "respostaID" => 356,
                "produtoID" => 516,
                "respostaPaiID" => 0,
                "respostaRegistro" => "N640",
                "respostaSubtipo" => "99",
                "respostaNome" => "Caso o Faturamento não seja calculado Este registro poderá ocorrer até 10 vezes",
                "respostaAgruparColunas" => 2,
                "respostaQtdeColunas" => null,
                "respostaDataCancel" => "1901-01-01 00:00:00",
                "usuarioIDCancel" => null,
                "respostaVisivelCliente" => 1,
                "respostaFlagRestricao" => 2,
                "respostaNumeroOrdem" => 44,
                "respostaInformativo" => "",
            ],
            [
                "respostaID" => 357,
                "produtoID" => 516,
                "respostaPaiID" => 0,
                "respostaRegistro" => "N650",
                "respostaSubtipo" => "00",
                "respostaNome" => "Dados do logradouro",
                "respostaAgruparColunas" => 2,
                "respostaQtdeColunas" => null,
                "respostaDataCancel" => "1901-01-01 00:00:00",
                "usuarioIDCancel" => null,
                "respostaVisivelCliente" => 1,
                "respostaFlagRestricao" => 2,
                "respostaNumeroOrdem" => 45,
                "respostaInformativo" => "",
            ],
            [
                "respostaID" => 358,
                "produtoID" => 516,
                "respostaPaiID" => 0,
                "respostaRegistro" => "N650",
                "respostaSubtipo" => "01",
                "respostaNome" => "Complemento do Endereço",
                "respostaAgruparColunas" => 2,
                "respostaQtdeColunas" => null,
                "respostaDataCancel" => "1901-01-01 00:00:00",
                "usuarioIDCancel" => null,
                "respostaVisivelCliente" => 1,
                "respostaFlagRestricao" => 2,
                "respostaNumeroOrdem" => 46,
                "respostaInformativo" => "",
            ],
            [
                "respostaID" => 359,
                "produtoID" => 516,
                "respostaPaiID" => 0,
                "respostaRegistro" => "N650",
                "respostaSubtipo" => "02",
                "respostaNome" => "Dados do Município/telefone (estes registros podem ocorrer até 3 vezes)",
                "respostaAgruparColunas" => 2,
                "respostaQtdeColunas" => null,
                "respostaDataCancel" => "1901-01-01 00:00:00",
                "usuarioIDCancel" => null,
                "respostaVisivelCliente" => 1,
                "respostaFlagRestricao" => 2,
                "respostaNumeroOrdem" => 47,
                "respostaInformativo" => "",
            ],
            [
                "respostaID" => 360,
                "produtoID" => 516,
                "respostaPaiID" => 0,
                "respostaRegistro" => "N650",
                "respostaSubtipo" => "99",
                "respostaNome" => "Caso não existam informações",
                "respostaAgruparColunas" => 2,
                "respostaQtdeColunas" => null,
                "respostaDataCancel" => "1901-01-01 00:00:00",
                "usuarioIDCancel" => null,
                "respostaVisivelCliente" => 1,
                "respostaFlagRestricao" => 2,
                "respostaNumeroOrdem" => 48,
                "respostaInformativo" => "",
            ],
            [
                "respostaID" => 361,
                "produtoID" => 516,
                "respostaPaiID" => 0,
                "respostaRegistro" => "N660",
                "respostaSubtipo" => "00",
                "respostaNome" => "Indicador de Operaconalidade PJ",
                "respostaAgruparColunas" => 2,
                "respostaQtdeColunas" => null,
                "respostaDataCancel" => "1901-01-01 00:00:00",
                "usuarioIDCancel" => null,
                "respostaVisivelCliente" => 1,
                "respostaFlagRestricao" => 2,
                "respostaNumeroOrdem" => 49,
                "respostaInformativo" => "",
            ],
            [
                "respostaID" => 362,
                "produtoID" => 516,
                "respostaPaiID" => 0,
                "respostaRegistro" => "N660",
                "respostaSubtipo" => "99",
                "respostaNome" => "Caso não existam informações",
                "respostaAgruparColunas" => 2,
                "respostaQtdeColunas" => null,
                "respostaDataCancel" => "1901-01-01 00:00:00",
                "usuarioIDCancel" => null,
                "respostaVisivelCliente" => 1,
                "respostaFlagRestricao" => 2,
                "respostaNumeroOrdem" => 50,
                "respostaInformativo" => "",
            ],
            [
                "respostaID" => 363,
                "produtoID" => 516,
                "respostaPaiID" => 0,
                "respostaRegistro" => "F900",
                "respostaSubtipo" => "CLC7",
                "respostaNome" => "Feature Limite de Crédito",
                "respostaAgruparColunas" => 2,
                "respostaQtdeColunas" => null,
                "respostaDataCancel" => "1901-01-01 00:00:00",
                "usuarioIDCancel" => null,
                "respostaVisivelCliente" => 1,
                "respostaFlagRestricao" => 2,
                "respostaNumeroOrdem" => 51,
                "respostaInformativo" => "",
            ],
            [
                "respostaID" => 364,
                "produtoID" => 516,
                "respostaPaiID" => 0,
                "respostaRegistro" => "C210",
                "respostaSubtipo" => "1",
                "respostaNome" => "Localizador",
                "respostaAgruparColunas" => 2,
                "respostaQtdeColunas" => null,
                "respostaDataCancel" => "1901-01-01 00:00:00",
                "usuarioIDCancel" => null,
                "respostaVisivelCliente" => 1,
                "respostaFlagRestricao" => 2,
                "respostaNumeroOrdem" => 42,
                "respostaInformativo" => "",
            ],
            [
                "respostaID" => 365,
                "produtoID" => 516,
                "respostaPaiID" => 0,
                "respostaRegistro" => "C210",
                "respostaSubtipo" => "2",
                "respostaNome" => "Localizador",
                "respostaAgruparColunas" => 2,
                "respostaQtdeColunas" => null,
                "respostaDataCancel" => "1901-01-01 00:00:00",
                "usuarioIDCancel" => null,
                "respostaVisivelCliente" => 1,
                "respostaFlagRestricao" => 2,
                "respostaNumeroOrdem" => 41,
                "respostaInformativo" => "",
            ],
            [
                "respostaID" => 366,
                "produtoID" => 516,
                "respostaPaiID" => 0,
                "respostaRegistro" => "C210",
                "respostaSubtipo" => "3",
                "respostaNome" => "Localizador",
                "respostaAgruparColunas" => 2,
                "respostaQtdeColunas" => null,
                "respostaDataCancel" => "1901-01-01 00:00:00",
                "usuarioIDCancel" => null,
                "respostaVisivelCliente" => 1,
                "respostaFlagRestricao" => 2,
                "respostaNumeroOrdem" => 40,
                "respostaInformativo" => "",
            ],
            [
                "respostaID" => 367,
                "produtoID" => 516,
                "respostaPaiID" => 0,
                "respostaRegistro" => "C999",
                "respostaSubtipo" => "na",
                "respostaNome" => "Erro no localizador",
                "respostaAgruparColunas" => 2,
                "respostaQtdeColunas" => null,
                "respostaDataCancel" => "1901-01-01 00:00:00",
                "usuarioIDCancel" => null,
                "respostaVisivelCliente" => 1,
                "respostaFlagRestricao" => 2,
                "respostaNumeroOrdem" => 31,
                "respostaInformativo" => "",
            ],
            [
                "respostaID" => 368,
                "produtoID" => 516,
                "respostaPaiID" => 0,
                "respostaRegistro" => "B901",
                "respostaSubtipo" => "00",
                "respostaNome" => "Mensagem de erro de Pedido",
                "respostaAgruparColunas" => 2,
                "respostaQtdeColunas" => null,
                "respostaDataCancel" => "1901-01-01 00:00:00",
                "usuarioIDCancel" => null,
                "respostaVisivelCliente" => 1,
                "respostaFlagRestricao" => 2,
                "respostaNumeroOrdem" => 32,
                "respostaInformativo" => "",
            ],
            [
                "respostaID" => 369,
                "produtoID" => 516,
                "respostaPaiID" => 0,
                "respostaRegistro" => "N999",
                "respostaSubtipo" => "99",
                "respostaNome" => "Finalização",
                "respostaAgruparColunas" => 2,
                "respostaQtdeColunas" => null,
                "respostaDataCancel" => "1901-01-01 00:00:00",
                "usuarioIDCancel" => null,
                "respostaVisivelCliente" => 1,
                "respostaFlagRestricao" => 2,
                "respostaNumeroOrdem" => 33,
                "respostaInformativo" => "",
            ],
            [
                "respostaID" => 370,
                "produtoID" => 516,
                "respostaPaiID" => 0,
                "respostaRegistro" => "F900",
                "respostaSubtipo" => "0",
                "respostaNome" => "CONSULTA ANOTAÇÕES SPC-BRASIL",
                "respostaAgruparColunas" => 2,
                "respostaQtdeColunas" => null,
                "respostaDataCancel" => "1901-01-01 00:00:00",
                "usuarioIDCancel" => null,
                "respostaVisivelCliente" => 1,
                "respostaFlagRestricao" => 2,
                "respostaNumeroOrdem" => 34,
                "respostaInformativo" => "",
            ],
            [
                "respostaID" => 371,
                "produtoID" => 516,
                "respostaPaiID" => 0,
                "respostaRegistro" => "F900",
                "respostaSubtipo" => "1",
                "respostaNome" => "CONSULTA ANOTAÇÕES SPC-BRASIL",
                "respostaAgruparColunas" => 2,
                "respostaQtdeColunas" => null,
                "respostaDataCancel" => "1901-01-01 00:00:00",
                "usuarioIDCancel" => null,
                "respostaVisivelCliente" => 1,
                "respostaFlagRestricao" => 2,
                "respostaNumeroOrdem" => 35,
                "respostaInformativo" => "",
            ],
            [
                "respostaID" => 372,
                "produtoID" => 516,
                "respostaPaiID" => 0,
                "respostaRegistro" => "F900",
                "respostaSubtipo" => "2",
                "respostaNome" => "CONSULTA ANOTAÇÕES SPC-BRASIL",
                "respostaAgruparColunas" => 2,
                "respostaQtdeColunas" => null,
                "respostaDataCancel" => "1901-01-01 00:00:00",
                "usuarioIDCancel" => null,
                "respostaVisivelCliente" => 1,
                "respostaFlagRestricao" => 2,
                "respostaNumeroOrdem" => 36,
                "respostaInformativo" => "",
            ],
            [
                "respostaID" => 373,
                "produtoID" => 516,
                "respostaPaiID" => 0,
                "respostaRegistro" => "F900",
                "respostaSubtipo" => "3",
                "respostaNome" => "CONSULTA ANOTAÇÕES SPC-BRASIL",
                "respostaAgruparColunas" => 2,
                "respostaQtdeColunas" => null,
                "respostaDataCancel" => "1901-01-01 00:00:00",
                "usuarioIDCancel" => null,
                "respostaVisivelCliente" => 1,
                "respostaFlagRestricao" => 2,
                "respostaNumeroOrdem" => 37,
                "respostaInformativo" => "",
            ],
            [
                "respostaID" => 374,
                "produtoID" => 516,
                "respostaPaiID" => 0,
                "respostaRegistro" => "F900",
                "respostaSubtipo" => "0",
                "respostaNome" => "CONSULTA ANOTAÇÕES SPC-BRASIL",
                "respostaAgruparColunas" => 2,
                "respostaQtdeColunas" => null,
                "respostaDataCancel" => "1901-01-01 00:00:00",
                "usuarioIDCancel" => null,
                "respostaVisivelCliente" => 1,
                "respostaFlagRestricao" => 2,
                "respostaNumeroOrdem" => 38,
                "respostaInformativo" => "",
            ],
            [
                "respostaID" => 375,
                "produtoID" => 516,
                "respostaPaiID" => 0,
                "respostaRegistro" => "F900",
                "respostaSubtipo" => "4",
                "respostaNome" => "Consulta",
                "respostaAgruparColunas" => 2,
                "respostaQtdeColunas" => null,
                "respostaDataCancel" => "1901-01-01 00:00:00",
                "usuarioIDCancel" => null,
                "respostaVisivelCliente" => 1,
                "respostaFlagRestricao" => 2,
                "respostaNumeroOrdem" => 39,
                "respostaInformativo" => "",
            ],
            [
                "respostaID" => 376,
                "produtoID" => 516,
                "respostaPaiID" => 0,
                "respostaRegistro" => "F900",
                "respostaSubtipo" => "5",
                "respostaNome" => "CONSULTA",
                "respostaAgruparColunas" => 2,
                "respostaQtdeColunas" => null,
                "respostaDataCancel" => "1901-01-01 00:00:00",
                "usuarioIDCancel" => null,
                "respostaVisivelCliente" => 1,
                "respostaFlagRestricao" => 2,
                "respostaNumeroOrdem" => 52,
                "respostaInformativo" => "",
            ],
        ];

        $this->insert('respostas', $respostas);
    }
}
